version: "3.5"

services:
  mongo-unsecure:
    container_name: mongo-unsecure
    image: mongo:4.2
    ports:
      - 37027:27017
    # Tambahkan --auth setelah menambahkan user admin pada database admin
    # command: mongod
    command: mongod --auth